title = "Irfan Haziq's Blog"
baseURL = 'https://capangjabba.github.io/'
locale = 'en-us'
theme = "papermod"
enableInlineShortcodes = true
enableRobotsTXT = true
capitalizeListTitles = false
[pagination]

pagerSize = 6

[params]

description = "DevOps, Platform Engineering, CTF writeups and malware stuff by Irfan Haziq. More will come!"
author = "Irfan Haziq / Capang"
images = ["images/og-default.png"]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true

[params.assets]
favicon = "favicons/favicon.ico"
favicon16x16 = "favicons/favicon-16x16.png"
favicon32x32 = "favicons/favicon-32x32.png"
apple_touch_icon = "favicons/apple-touch-icon.png"
safari_pinned_tab = "favicons/safari-pinned-tab.svg"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params.homeInfoParams]
Title = "I'm Irfan Haziq / Capang"
Content = "I write about DevOps and Kubernetes, CTF challenges, malware analysis and there will be more to come! I have deep passion in learning about computers, so this is where I share it all."
[[params.socialIcons]]
name = "Github"
url = "https://github.com/capangjabba"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/gnapac/"

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 5

[[menu.main]]
name = "Series"
url = "series/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 15

[[menu.main]]
name = "Search"
url = "search/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[markup.goldmark.renderer]
unsafe = true
